name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main # BRANCH（キー名）：main（バリュー）
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}  # env コンテキスト経由でジョブレベルの環境変数を参照